'use client';

import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 30, backgroundColor: '#ffffff' },
  header: { marginBottom: 20, borderBottom: '2pt solid #0f4c3a', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#0f4c3a' },
  subtitle: { fontSize: 12, color: '#666666', marginTop: 4 },
  table: { display: 'flex', width: 'auto', borderStyle: 'solid', borderWidth: 1, borderColor: '#bfbfbf', marginBottom: 20 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderColor: '#bfbfbf' },
  tableHeader: { backgroundColor: '#f0f4f3', fontWeight: 'bold' },
  tableCol: { width: '25%', padding: 5 },
  tableCell: { fontSize: 10 },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, borderTopWidth: 1, borderColor: '#bfbfbf', paddingTop: 10, fontSize: 8, color: '#999999', textAlign: 'center' }
});

export function InventoryReport({ data, storeName }: { data: any[], storeName: string }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>PillOps Inventory Report</Text>
          <Text style={styles.subtitle}>{storeName} • {new Date().toLocaleDateString()}</Text>
        </View>

        <View style={styles.table}>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <View style={[styles.tableCol, { width: '40%' }]}><Text style={styles.tableCell}>Medicine Name</Text></View>
            <View style={[styles.tableCol, { width: '20%' }]}><Text style={styles.tableCell}>Category</Text></View>
            <View style={[styles.tableCol, { width: '20%' }]}><Text style={styles.tableCell}>Stock</Text></View>
            <View style={[styles.tableCol, { width: '20%' }]}><Text style={styles.tableCell}>Status</Text></View>
          </View>
          {data.map((item, i) => (
            <View key={i} style={styles.tableRow}>
              <View style={[styles.tableCol, { width: '40%' }]}><Text style={styles.tableCell}>{item.name}</Text></View>
              <View style={[styles.tableCol, { width: '20%' }]}><Text style={styles.tableCell}>{item.category}</Text></View>
              <View style={[styles.tableCol, { width: '20%' }]}><Text style={styles.tableCell}>{item.totalQty}</Text></View>
              <View style={[styles.tableCol, { width: '20%' }]}><Text style={styles.tableCell}>{item.overallExpiryStatus}</Text></View>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by PillOps – Smart Pharmacy Operations. This is a system-generated report.
        </Text>
      </Page>
    </Document>
  );
}
