-- Seed Indian drug manufacturers
INSERT INTO "manufacturers" (name)
VALUES
  ('Sun Pharmaceutical Industries Ltd'),
  ('Dr. Reddy''s Laboratories'),
  ('Cipla'),
  ('Divi''s Laboratories'),
  ('Aurobindo Pharma'),
  ('Torrent Pharmaceuticals'),
  ('Lupin Limited'),
  ('Zydus Lifesciences'),
  ('Alkem Laboratories'),
  ('Mankind Pharma'),
  ('Biocon Limited'),
  ('Glenmark Pharmaceuticals'),
  ('Intas Pharmaceuticals'),
  ('Macleods Pharmaceuticals'),
  ('Aristo Pharmaceuticals'),
  ('Emcure Pharmaceuticals'),
  ('IPCA Laboratories'),
  ('Alembic Pharmaceuticals'),
  ('Natco Pharma'),
  ('Ajanta Pharma'),
  ('J.B. Chemicals & Pharmaceuticals'),
  ('Eris Lifesciences'),
  ('Suven Pharmaceuticals'),
  ('Abbott India'),
  ('GlaxoSmithKline Pharmaceuticals (India)'),
  ('Pfizer Ltd (India)'),
  ('Sanofi India'),
  ('AstraZeneca Pharma India'),
  ('Procter & Gamble Health'),
  ('FDC Limited'),
  ('Indoco Remedies'),
  ('Granules India'),
  ('Shilpa Medicare'),
  ('Wockhardt Limited'),
  ('Unichem Laboratories'),
  ('Strides Pharma Science'),
  ('Jubilant Pharmova'),
  ('Hetero Drugs'),
  ('Laurus Labs'),
  ('Gland Pharma'),
  ('Piramal Pharma'),
  ('Micro Labs'),
  ('USV Private Limited'),
  ('Blue Cross Laboratories'),
  ('Franco-Indian Pharmaceuticals'),
  ('Wallace Pharmaceuticals'),
  ('Koye Pharmaceuticals'),
  ('Troikaa Pharmaceuticals'),
  ('Corona Remedies'),
  ('RPG Life Sciences'),
  ('Apex Laboratories'),
  ('Curatio Healthcare'),
  ('Zuventus Healthcare'),
  ('Meyer Organics'),
  ('Systopic Laboratories'),
  ('Fourrts (India) Laboratories'),
  ('Medley Pharmaceuticals'),
  ('Tablets India'),
  ('Panacea Biotec'),
  ('Lincoln Pharmaceuticals'),
  ('Albert David Limited'),
  ('Morepen Laboratories'),
  ('Marksans Pharma'),
  ('Nectar Lifesciences'),
  ('SMS Pharmaceuticals')
ON CONFLICT (name) DO NOTHING;
